load File.join(File.dirname(__FILE__), '..', '.flutter-plugins-dependencies') if File.exist?(File.join(File.dirname(__FILE__), '..', '.flutter-plugins-dependencies'))

platform :ios, '13.0'

target_path = File.join(File.dirname(__FILE__), '..', '.flutter-plugins-dependencies')
if File.exist?(target_path)
  prop = eval(File.read(target_path))
  if prop.key?('plugins') && prop['plugins'].key?('ios')
    load File.join(prop['plugins']['ios'], 'package', 'framework', 'cocoapods_support.rb') if File.exist?(File.join(prop['plugins']['ios'], 'package', 'framework', 'cocoapods_support.rb'))
  end
end

def flutter_install_all_ios_pods(ios_application_path = nil)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
